### ISSUE TITLE
Notary contract

### ISSUE THREAD

**Issue by akshithg** [LegalEntity/BlockchainNotarization#2]
Create a Notary Contract on ethereum, primary functionality is to be able to show proof of existence.

**Comment by akshithg** [comment]
@dazzaji commit f28aec2a47ed96e4b6d96a6e9233c61aedba5d10 has a Notary contract which can map hash of a document to an address (public key) of the owner.

A web interface isn't ready yet, but we can use the  ethereum wallet and deploy the contract and test the functionality.

Let me know a good time for a demo.

**Comment by dazzaji** [comment]
Wow - this looks great at first glance!  Do you have time to demo later today (after 2pm Eastern)?

**Comment by akshithg** [comment]
Sure @dazzaji between 2pm-3pm Eastern?

**Comment by dazzaji** [comment]
Caitlin and I are presenting a rapid hack of automated and blockchain
connected revolving loan fund at Distributed Health hackathon ending 2:15..
is possible to plan for 2:45 and can you ring me please?

---

   |   Daniel "Dazza" Greenwood dazza@civics.com
   |   CIVICS.com http://civics.com/ & Law.MIT.edu http://law.mit.edu/
   |   One Broadway, 14th Fl, Cambridge, Mass

**Comment by akshithg** [comment]
Dazza that'll be a little late here. Can we do it the day after if that works for you? In the mean time I'll put up the setup instructions. You can try it by yourself meanwhile.

**Comment by tomwro** [comment]
Wow! Quick work. I don’t have time today to do a demo, but I’ll go in an look at it ASAP.

Thanks,

Tom
